### ISSUE TITLE
After build this it doesn't work

### ISSUE THREAD

**Issue by t42ji2ji** [TermiT/iCloudKeyValue#1]
it comes this error.
I had opened icloud in Capbility

`DllNotFoundException: Unable to load DLL 'iCloudKeyValue': The specified module could not be found.
  at test.iCloudKV_Synchronize () [0x00000] in <filename unknown>:0 
  at test.Start () [0x00000] in <filename unknown>:0 
 
(Filename: currently not available on il2cpp Line: -1)

DllNotFoundException: Unable to load DLL 'iCloudKeyValue': The specified module could not be found.
  at IosFuc.iCloudKV_Synchronize () [0x00000] in <filename unknown>:0 
  at IosFuc.Start () [0x00000] in <filename unknown>:0 
 
(Filename: currently not available on il2cpp Line: -1)

Setting up 1 worker threads for Enlighten.
  Thread -> id: 16e8ef000 -> priority: 1 
-> applicationWillResignActive()
-> applicationDidEnterBackground()`

**Comment by TermiT** [comment]
do you use it for iOS or Mac?

**Comment by t42ji2ji** [comment]
im using it on iOS after I change  [DllImport("iCloudKeyValue")] to     [DllImport("__Internal")]
it can work but the icloudkv always be 1 wont change to 2

**Comment by TermiT** [comment]
Make sure that you setup properly iCloudKeyValue provision/entitlements/etc

**Comment by t42ji2ji** [comment]
Okay Is it possible to make a version that i can store string using icloud keyvalue?

**Comment by TermiT** [comment]
Create a separate issue ticket for this request
