### ISSUE TITLE
Use of the iCloudKV_Synchronize method

### ISSUE THREAD

**Issue by felipe-cb** [TermiT/iCloudKeyValue#2]
Hi there,

I'm sorry if there's an obvious answer to this, but... what exactly should the Synchronize method do?

When I call it, my PlayerPrefs data is not updated with the values that are on iCloud, nor do the iCloud values get updated with the PlayerPrefs values. 

When I call the Set Int or Float values of the iCloud, they are automatically submitted to the iCloud - no need to call Synchronize.

So how exactly am I supposed to use it? Is there a way to sync local and cloud data (the older one gets updated with the newer one) or am I supposed to do it manually?

Best,
Felipe

**Comment by TermiT** [comment]
iCloudKV_Synchronize has nothing to do with PlayerPrefs. iCloudKV_Synchronize is to force iCloud sync. It's not required to call it after every operation unless your app design requires fast-as-possible upload to iCloud after you change a value. The only recommended time to call this method is upon app launch, or upon returning to the foreground, to ensure that the in-memory key-value store representation is up-to-date.
